### ISSUE TITLE
error when building chrome (crx3, build-post.js)

### ISSUE THREAD

**Issue by budRich** [lydell/LinkHints#26]
Hello I have been hacking on this excellent extension and there seems to be something off in the build process.

When doing build:chrome the operation exits with an error, i get this message:  

```
Applying config files: ./package.json, ./web-ext-config.js
Building web extension from /home/bud/git/frk/LinkHints/compiled
Your web extension is ready: dist-chrome/link_hints-1.1.1.zip

> @ build-post /home/bud/git/frk/LinkHints
> sucrase-node scripts/build-post.js

/home/bud/git/frk/LinkHints/node_modules/crx3/lib/crx3stream.js:142
		const done2 = err => super._final(err2 => callback(err || err2) || (this.crx = null)); // eslint-disable-line no-return-assign
		                           ^

TypeError: (intermediate value)._final is not a function
    at done2 (/home/bud/git/frk/LinkHints/node_modules/crx3/lib/crx3stream.js:142:30)
    at /home/bud/git/frk/LinkHints/node_modules/crx3/lib/crx3stream.js:143:51
    at FSReqCallback.oncomplete (node:fs:184:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build-post: `sucrase-node scripts/build-post.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build-post script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bud/.npm/_logs/2021-02-01T21_13_28_482Z-debug.log
ERROR: "build-post" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:chrome: `cross-env BROWSER=chrome run-s compile build-clean "web-ext -- build" build-post`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build:chrome script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bud/.npm/_logs/2021-02-01T21_13_28_509Z-debug.log
ERROR: "build:chrome" exited with 1.
```

The extension is compiled and packed successfully both in the compiled directory and as crx and zip files with the key.pem file , so everything works. 

When building for firefox i don't get any critical errors. 

also, i use these guys to build:  
```
npm@6.14.11
node@v15.7.0
```

**Comment by lydell** [comment]
> Hello I have been hacking on this excellent extension

Hi. Thank you! ❤️ 

> there seems to be something off in the build process

I get that error too on Node.js 15, but not on Node.js 14.

I’ll look into this more once I get back to working on this extension again. I’ve been wanting to do a few tweaks for a while, but have ended up working on other open source projects. My hope is to give this repo some love during the first half of this year.

**Comment by lydell** [comment]
Turns out all I needed to do was to update crx3 to the latest version. It should now work on Node.js 15+!

**Comment by budRich** [comment]
Sweet!
